/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package base.de.datos.mantenimiento;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Noktuapc
 */
public class josuellorona extends javax.swing.JFrame {
  Conexion con= new Conexion();
  
  //VARIABLE PARA CAPTURAR EL ID DEL CLIENTE y REFACCION
  String idCliente = null, idRefaccion = null;

    /**
     * Creates new form josuellorona
     */
    public josuellorona() {
        initComponents();
        this.setLocationRelativeTo(null);
        pedidos();
        automovil();
        clientes();
        refacciones();
        comboClientes();
        comboRefaccion();
    }
    
    //TABLA PEDIDOS
    public void pedidos (){
        con.tabla("Select p.id_pedido, nombre, p.fecha_pedido, p.estado, p.cantidad from pedidos as p, refacciones where p.refaccion = refacciones.id_refaccion",tablapedidos.getModel());
    }
    
    //TABLA AUTOMOVIL
    public void automovil(){
        con.tabla("select a.ID_AUTO,a.VIN,concat(c.nombre, ' ', c.app, ' ', c.apm) as CLIENTE, a.nombre, a.modelo from automovil as a,clientes as c\n" +
        "where a.CLIENTE = c.id_cliente;",tablautomovil.getModel());
    }
    
    //TABLA AUTOMOVIL
    public void clientes(){
        con.tabla("Select * from clientes;",tablaclientes.getModel());
    }
    
    //TABLA REFACCIONES
    public void refacciones(){
        con.tabla("Select * from refacciones;", tablarefacciones.getModel());
    }
    
    //CAPTURAR CLIENTES PARA AGREGARLOS AL COMBOBOX
    public void comboClientes(){
        try {
            ResultSet rs = con.st.executeQuery("select concat(nombre,' ',app,' ',apm) from clientes;");
            while(rs.next()){
                cmbcliente.addItem(rs.getString(1));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    //CAPTURAR ID DEL CLIENTE
    private void idCliente(){
        try {
            ResultSet rs = con.st.executeQuery("select id_cliente from clientes where concat(nombre,' ',app,' ',apm) = '"+cmbcliente.getSelectedItem()+"'");
            rs.last();
            idCliente = rs.getString(1);
        }catch (SQLException e) {
            System.out.println(e.getErrorCode());
        }
    }
    //CAPTURAR REFACCIONES PARA AGREGARLAS AL COMBOBOX
    private void comboRefaccion(){
      try {
          ResultSet rs = con.st.executeQuery("select nombre from refacciones;");
          while(rs.next()){
              pcmbrefaccion.addItem(rs.getString(1));
          }
      } catch (SQLException e) {
          System.out.println(e.getErrorCode());
      }
    }
    
    //CAPTURAR ID DE LA REFACCION
    private void idRefaccion(){
      try {
          ResultSet rs = con.st.executeQuery("select id_refaccion from refacciones where nombre = '"+pcmbrefaccion.getSelectedItem()+"';");
          rs.last();
          idRefaccion = rs.getString(1);
      } catch (SQLException ex) {
          Logger.getLogger(josuellorona.class.getName()).log(Level.SEVERE, null, ex);
      }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab5 = new javax.swing.JTabbedPane();
        panelpedidos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablapedidos = new javax.swing.JTable();
        idpedido = new javax.swing.JTextField();
        estado = new javax.swing.JTextField();
        btnInsertarPedidos = new javax.swing.JButton();
        btnModificarPedidos = new javax.swing.JButton();
        btnEliminarPedidos = new javax.swing.JButton();
        pcmbrefaccion = new javax.swing.JComboBox();
        fechapedido = new javax.swing.JFormattedTextField();
        pcantidad = new javax.swing.JTextField();
        panelautomovil = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablautomovil = new javax.swing.JTable();
        anumserie = new javax.swing.JTextField();
        anombre = new javax.swing.JTextField();
        amodelo = new javax.swing.JTextField();
        aidvehiculo = new javax.swing.JTextField();
        cmbcliente = new javax.swing.JComboBox<String>();
        insertarautomovil = new javax.swing.JButton();
        modificarautomovil = new javax.swing.JButton();
        eliminarautomovil = new javax.swing.JButton();
        panelrefacciones = new javax.swing.JPanel();
        rtxtidrefaccion = new javax.swing.JTextField();
        rtxtcantidad = new javax.swing.JTextField();
        rtxtcosto = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablarefacciones = new javax.swing.JTable();
        rtxtnombre = new javax.swing.JTextField();
        btnInsertarRefaccion = new javax.swing.JButton();
        btnModificarRefaccion = new javax.swing.JButton();
        btnEliminarRefaccion = new javax.swing.JButton();
        panelingresos = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        panelservicios = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jTextField3 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<String>();
        jTextField20 = new javax.swing.JTextField();
        clientes = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaclientes = new javax.swing.JTable();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablapedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablapedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablapedidosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablapedidos);

        idpedido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        idpedido.setForeground(new java.awt.Color(153, 153, 153));
        idpedido.setText("Id Pedido");
        idpedido.setPreferredSize(new java.awt.Dimension(73, 31));

        estado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        estado.setForeground(new java.awt.Color(153, 153, 153));
        estado.setText("Estado");

        btnInsertarPedidos.setText("Insertar");
        btnInsertarPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarPedidosActionPerformed(evt);
            }
        });

        btnModificarPedidos.setText("Modificar");
        btnModificarPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarPedidosActionPerformed(evt);
            }
        });

        btnEliminarPedidos.setText("Eliminar");
        btnEliminarPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPedidosActionPerformed(evt);
            }
        });

        pcmbrefaccion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Refaccion" }));

        try {
            fechapedido.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        pcantidad.setText("Cantidad");

        javax.swing.GroupLayout panelpedidosLayout = new javax.swing.GroupLayout(panelpedidos);
        panelpedidos.setLayout(panelpedidosLayout);
        panelpedidosLayout.setHorizontalGroup(
            panelpedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelpedidosLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 821, Short.MAX_VALUE))
            .addGroup(panelpedidosLayout.createSequentialGroup()
                .addGroup(panelpedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelpedidosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnInsertarPedidos)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificarPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarPedidos))
                    .addGroup(panelpedidosLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(idpedido, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pcmbrefaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fechapedido, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelpedidosLayout.setVerticalGroup(
            panelpedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelpedidosLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelpedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idpedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelpedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pcmbrefaccion)
                        .addComponent(fechapedido, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelpedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertarPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tab5.addTab("Pedidos", panelpedidos);

        tablautomovil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablautomovil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablautomovilMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablautomovil);

        anumserie.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        anumserie.setForeground(new java.awt.Color(153, 153, 153));
        anumserie.setText("Num. Serie");

        anombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        anombre.setForeground(new java.awt.Color(153, 153, 153));
        anombre.setText("Nombre");

        amodelo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        amodelo.setForeground(new java.awt.Color(153, 153, 153));
        amodelo.setText("Modelo");

        aidvehiculo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        aidvehiculo.setForeground(new java.awt.Color(153, 153, 153));
        aidvehiculo.setText("Id_Vehiculo");

        cmbcliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbcliente.setForeground(new java.awt.Color(153, 153, 153));
        cmbcliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cliente" }));

        insertarautomovil.setText("Insertar");
        insertarautomovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarautomovilActionPerformed(evt);
            }
        });

        modificarautomovil.setText("Modificar");
        modificarautomovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarautomovilActionPerformed(evt);
            }
        });

        eliminarautomovil.setText("Eliminar");
        eliminarautomovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarautomovilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelautomovilLayout = new javax.swing.GroupLayout(panelautomovil);
        panelautomovil.setLayout(panelautomovilLayout);
        panelautomovilLayout.setHorizontalGroup(
            panelautomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(panelautomovilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelautomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelautomovilLayout.createSequentialGroup()
                        .addComponent(insertarautomovil, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(modificarautomovil, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(eliminarautomovil, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelautomovilLayout.createSequentialGroup()
                        .addComponent(anumserie, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(anombre, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(amodelo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(aidvehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        panelautomovilLayout.setVerticalGroup(
            panelautomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelautomovilLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(panelautomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anumserie, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amodelo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aidvehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelautomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertarautomovil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modificarautomovil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminarautomovil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tab5.addTab("Automovil", panelautomovil);

        rtxtidrefaccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rtxtidrefaccion.setForeground(new java.awt.Color(153, 153, 153));
        rtxtidrefaccion.setText("Id_Refaccion");

        rtxtcantidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rtxtcantidad.setForeground(new java.awt.Color(153, 153, 153));
        rtxtcantidad.setText("Cantidad");

        rtxtcosto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rtxtcosto.setForeground(new java.awt.Color(153, 153, 153));
        rtxtcosto.setText("Costo");

        tablarefacciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tablarefacciones);

        rtxtnombre.setText("Nombre");

        btnInsertarRefaccion.setText("Insertar");
        btnInsertarRefaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarRefaccionActionPerformed(evt);
            }
        });

        btnModificarRefaccion.setText("Modificar");
        btnModificarRefaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarRefaccionActionPerformed(evt);
            }
        });

        btnEliminarRefaccion.setText("Eliminar");
        btnEliminarRefaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarRefaccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelrefaccionesLayout = new javax.swing.GroupLayout(panelrefacciones);
        panelrefacciones.setLayout(panelrefaccionesLayout);
        panelrefaccionesLayout.setHorizontalGroup(
            panelrefaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelrefaccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelrefaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelrefaccionesLayout.createSequentialGroup()
                        .addComponent(rtxtidrefaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rtxtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rtxtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rtxtcosto, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(247, 247, 247))
                    .addGroup(panelrefaccionesLayout.createSequentialGroup()
                        .addComponent(jScrollPane5)
                        .addContainerGap())
                    .addGroup(panelrefaccionesLayout.createSequentialGroup()
                        .addComponent(btnInsertarRefaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificarRefaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarRefaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelrefaccionesLayout.setVerticalGroup(
            panelrefaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelrefaccionesLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(panelrefaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rtxtcosto, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(rtxtcantidad, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rtxtidrefaccion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rtxtnombre))
                .addGap(18, 18, 18)
                .addGroup(panelrefaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertarRefaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarRefaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarRefaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tab5.addTab("Refacciones y Consumibles", panelrefacciones);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setText("Id Ingreso");

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        jTextField2.setText("Ingreso");

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(153, 153, 153));
        jTextField4.setText("Servicio");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jFormattedTextField1.setForeground(new java.awt.Color(153, 153, 153));
        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField1.setCaretColor(new java.awt.Color(153, 153, 153));
        jFormattedTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout panelingresosLayout = new javax.swing.GroupLayout(panelingresos);
        panelingresos.setLayout(panelingresosLayout);
        panelingresosLayout.setHorizontalGroup(
            panelingresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(panelingresosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(264, Short.MAX_VALUE))
        );
        panelingresosLayout.setVerticalGroup(
            panelingresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelingresosLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(panelingresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tab5.addTab("Ingresos", panelingresos);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(153, 153, 153));
        jTextField3.setText("Nombre");

        jTextField14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField14.setForeground(new java.awt.Color(153, 153, 153));
        jTextField14.setText("Auto_id");

        jFormattedTextField2.setForeground(new java.awt.Color(153, 153, 153));
        try {
            jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField2.setCaretColor(new java.awt.Color(153, 153, 153));
        jFormattedTextField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextField15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField15.setForeground(new java.awt.Color(153, 153, 153));
        jTextField15.setText("Cliente");

        jTextField19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField19.setForeground(new java.awt.Color(153, 153, 153));
        jTextField19.setText("Costo");

        jComboBox3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(153, 153, 153));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cliente" }));

        jTextField20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField20.setForeground(new java.awt.Color(153, 153, 153));
        jTextField20.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField20.setText("Auto_id");

        javax.swing.GroupLayout panelserviciosLayout = new javax.swing.GroupLayout(panelservicios);
        panelservicios.setLayout(panelserviciosLayout);
        panelserviciosLayout.setHorizontalGroup(
            panelserviciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 821, Short.MAX_VALUE)
            .addGroup(panelserviciosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelserviciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelserviciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelserviciosLayout.createSequentialGroup()
                        .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField20))
                .addGap(18, 18, 18)
                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelserviciosLayout.setVerticalGroup(
            panelserviciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelserviciosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelserviciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelserviciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField20)
                    .addGroup(panelserviciosLayout.createSequentialGroup()
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 15, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tab5.addTab("Servicios", panelservicios);

        tablaclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tablaclientes);

        jTextField21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField21.setForeground(new java.awt.Color(153, 153, 153));
        jTextField21.setText("Id_cliente");

        jTextField22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField22.setForeground(new java.awt.Color(153, 153, 153));
        jTextField22.setText("Nombre");

        jTextField23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField23.setForeground(new java.awt.Color(153, 153, 153));
        jTextField23.setText("App");

        jTextField24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField24.setForeground(new java.awt.Color(153, 153, 153));
        jTextField24.setText("Apm");

        jTextField25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField25.setForeground(new java.awt.Color(153, 153, 153));
        jTextField25.setText("Telefono");

        jTextField26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField26.setForeground(new java.awt.Color(153, 153, 153));
        jTextField26.setText("Correo");

        javax.swing.GroupLayout clientesLayout = new javax.swing.GroupLayout(clientes);
        clientes.setLayout(clientesLayout);
        clientesLayout.setHorizontalGroup(
            clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 821, Short.MAX_VALUE)
            .addGroup(clientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField26)
                    .addComponent(jTextField21, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        clientesLayout.setVerticalGroup(
            clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tab5.addTab("Clientes", clientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab5, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab5, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarPedidosActionPerformed
        if(pcmbrefaccion.getSelectedItem().equals("Refaccion")){
            JOptionPane.showMessageDialog(null, "Seleccione la REFACCION a pedir");
        }else{
            idRefaccion();
            con.insertaryact("Insert Into pedidos values('"+idpedido.getText()+"','"+idRefaccion+"','"+fechapedido.getText()+"','"+estado.getText()+"',"+pcantidad.getText()+");");
            pedidos(); 
        }

    }//GEN-LAST:event_btnInsertarPedidosActionPerformed

    private void btnModificarPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarPedidosActionPerformed
        if(pcmbrefaccion.getSelectedItem().equals("Refaccion")){
            JOptionPane.showMessageDialog(null, "Seleccione la REFACCION a pedir");
        }else{
            idRefaccion();
            con.insertaryact("Update pedidos set refaccion='"+idRefaccion+"',fecha_pedido= '"+fechapedido.getText()+"',estado ='"+estado.getText()+"', cantidad='"+pcantidad.getText()+"' where id_pedido= '"+idpedido.getText()+"';");
            pedidos();
        }
    }//GEN-LAST:event_btnModificarPedidosActionPerformed

    private void btnEliminarPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPedidosActionPerformed
        con.eliminar("Delete From pedidos where id_pedido='"+idpedido.getText()+"';");
        pedidos();
    }//GEN-LAST:event_btnEliminarPedidosActionPerformed

    private void tablapedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablapedidosMouseClicked
        int fila= tablapedidos.getSelectedRow();
        idpedido.setText(tablapedidos.getValueAt(fila, 0).toString());
        pcmbrefaccion.setSelectedItem(tablapedidos.getValueAt(fila, 1).toString());
        fechapedido.setText(tablapedidos.getValueAt(fila,2).toString());
        estado.setText(tablapedidos.getValueAt(fila,3).toString());
        pcantidad.setText(tablapedidos.getValueAt(fila,4).toString());
    }//GEN-LAST:event_tablapedidosMouseClicked

    private void insertarautomovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarautomovilActionPerformed
        if(cmbcliente.getSelectedItem().equals("Cliente")){
            JOptionPane.showMessageDialog(null, "Seleccione un Cliente");
        }else{
            idCliente();
            con.insertaryact("Insert Into automovil values('"+aidvehiculo.getText()+"','"+anumserie.getText()+"','"+idCliente+"','"+amodelo.getText()+"','"+anombre.getText()+"' );");
            automovil();
        }
    }//GEN-LAST:event_insertarautomovilActionPerformed

    private void modificarautomovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarautomovilActionPerformed
        if(cmbcliente.getSelectedItem().equals("Cliente")){
            JOptionPane.showMessageDialog(null, "Seleccione un Cliente");
        }else{
            idCliente();
            con.insertaryact("Update automovil set nombre='"+anombre.getText()+"',modelo ='"+amodelo.getText()+"',vin= '"+anumserie.getText()+"',cliente ='"+idCliente+"' where id_auto= '"+aidvehiculo.getText()+"';");
            automovil();    
        }
    }//GEN-LAST:event_modificarautomovilActionPerformed

    private void eliminarautomovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarautomovilActionPerformed
        con.eliminar("Delete From automovil where id_auto='"+aidvehiculo.getText()+"';");
        automovil();
    }//GEN-LAST:event_eliminarautomovilActionPerformed

    private void tablautomovilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablautomovilMouseClicked
        int fila= tablautomovil.getSelectedRow();
        aidvehiculo.setText(tablautomovil.getValueAt(fila, 0).toString());
        anumserie.setText(tablautomovil.getValueAt(fila, 1).toString());
        cmbcliente.setSelectedItem(tablautomovil.getValueAt(fila,2).toString());
        anombre.setText(tablautomovil.getValueAt(fila,3).toString());
        amodelo.setText(tablautomovil.getValueAt(fila,4).toString());
    }//GEN-LAST:event_tablautomovilMouseClicked

    private void btnInsertarRefaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarRefaccionActionPerformed
        con.insertaryact("insert into refacciones values('"+rtxtidrefaccion.getText()+"','"+rtxtnombre.getText()+"',"+rtxtcantidad.getText()+","+rtxtcosto.getText()+");");
        refacciones();
    }//GEN-LAST:event_btnInsertarRefaccionActionPerformed

    private void btnModificarRefaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarRefaccionActionPerformed
        con.insertaryact("update refacciones set nombre=");
    }//GEN-LAST:event_btnModificarRefaccionActionPerformed

    private void btnEliminarRefaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarRefaccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarRefaccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(josuellorona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(josuellorona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(josuellorona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(josuellorona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new josuellorona().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aidvehiculo;
    private javax.swing.JTextField amodelo;
    private javax.swing.JTextField anombre;
    private javax.swing.JTextField anumserie;
    private javax.swing.JButton btnEliminarPedidos;
    private javax.swing.JButton btnEliminarRefaccion;
    private javax.swing.JButton btnInsertarPedidos;
    private javax.swing.JButton btnInsertarRefaccion;
    private javax.swing.JButton btnModificarPedidos;
    private javax.swing.JButton btnModificarRefaccion;
    private javax.swing.JPanel clientes;
    private javax.swing.JComboBox<String> cmbcliente;
    private javax.swing.JButton eliminarautomovil;
    private javax.swing.JTextField estado;
    private javax.swing.JFormattedTextField fechapedido;
    private javax.swing.JTextField idpedido;
    private javax.swing.JButton insertarautomovil;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton modificarautomovil;
    private javax.swing.JPanel panelautomovil;
    private javax.swing.JPanel panelingresos;
    private javax.swing.JPanel panelpedidos;
    private javax.swing.JPanel panelrefacciones;
    private javax.swing.JPanel panelservicios;
    private javax.swing.JTextField pcantidad;
    private javax.swing.JComboBox pcmbrefaccion;
    private javax.swing.JTextField rtxtcantidad;
    private javax.swing.JTextField rtxtcosto;
    private javax.swing.JTextField rtxtidrefaccion;
    private javax.swing.JTextField rtxtnombre;
    private javax.swing.JTabbedPane tab5;
    private javax.swing.JTable tablaclientes;
    private javax.swing.JTable tablapedidos;
    private javax.swing.JTable tablarefacciones;
    private javax.swing.JTable tablautomovil;
    // End of variables declaration//GEN-END:variables
}
